apiVersion: apps/v1
kind: Deployment
metadata:
  name: agreementsservice-deployment
  labels:
    app: AgreementsService
    name: agreementsservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: AgreementsService

 #-------------------------------> RollingUpdate definition
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 50%

#-------------------------------> Blueprint for Pod
  template:
    metadata:
      labels:
        app: AgreementsService
    spec:
      containers:
      - name: agreementsservice
        image: crfitverse.azurecr.io/agreementsservice:$(Build.BuildId)
        ports:
        - containerPort: 5005
        - name: health-port
          containerPort: 80
          #hostPort: 80
        env:
        - name: ConnectionStrings__0__DockerDb
          value: "test"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: as-service
spec:
  selector:
    app: AgreementsService
  ports:
    - protocol: TCP
      port: 85
      targetPort: 5005
